### ISSUE TITLE
Document non-Python requirements for Elekto

### ISSUE THREAD

**Issue by jberkus** [elekto-io/elekto#23]
While Python requirements are in requirements.txt, we need all the non-python stuff.

**Comment by kalkayan** [comment]
![image](https://user-images.githubusercontent.com/73003119/105520970-548fe900-5d01-11eb-85de-3fc4a4c10365.png)

This is the only error that anyone might face while installation, below is the fix:

```bash
sudo apt-get install libmysqlclient-dev
```

**Comment by kalkayan** [comment]
## Python Installation 

```bash
sudo apt update
sudo apt install software-properties-common
sudo apt install python3.8

# pip Installation
sudo apt install python3-pip
```

**Comment by jberkus** [comment]
What about git and related tools?

**Comment by kalkayan** [comment]
only `git`was a prerequisite it the base image is ubuntu we should stick 
```bash
sudo apt-get install git software-properties-common python3.8 python3-pip libmysqlclient-dev
```

**Comment by jberkus** [comment]
thanks

**Comment by jberkus** [comment]
done.
