### ISSUE TITLE
Some logo options for elekto

### ISSUE THREAD

**Issue by kalkayan** [elekto-io/elekto#27]
Yesterday, I got to know about the knative's upcoming election. So I was wondering if we should properly configure the application on the UI side (in a lot of places it still shows Kubernetes). 

Attaching Some Logo, Please give your reviews.

@jberkus

**Comment by kalkayan** [comment]
![2](https://user-images.githubusercontent.com/73003119/115706941-cf61b200-a38b-11eb-916e-dacfc422bc1e.png)

**Comment by kalkayan** [comment]
![banner](https://user-images.githubusercontent.com/73003119/115707295-35e6d000-a38c-11eb-82d8-4799cdcb3a41.png)

**Comment by kalkayan** [comment]
![2](https://user-images.githubusercontent.com/73003119/115709107-6af42200-a38e-11eb-826d-bcaf157e2e2a.png)

**Comment by kalkayan** [comment]
<div style="display:flex;">
<img width="250" src="https://user-images.githubusercontent.com/73003119/115709335-bdcdd980-a38e-11eb-8af9-060e3bd3ee98.png" />
<img width="250" src="https://user-images.githubusercontent.com/73003119/115709184-865f2d00-a38e-11eb-8f36-4cbf213d1a81.png" />
<img width="250" src="https://user-images.githubusercontent.com/73003119/115709328-bc041600-a38e-11eb-85bc-08347976f721.png" />
</div>

**Comment by kalkayan** [comment]
Tested the UI with new images.

<img width="1552" alt="Screenshot 2021-04-22 at 6 55 46 PM" src="https://user-images.githubusercontent.com/73003119/115722178-5b7bd580-a39c-11eb-8165-2dd933a1b8ee.png">

**Comment by jberkus** [comment]
Sure, works for me!  I especially like #2.
