### ISSUE TITLE
Implement security recommendations

### ISSUE THREAD

**Issue by jberkus** [elekto-io/elekto#51]
We have had a security audit by the Kubernetes security team.  They helpfully identified a number of areas of improvement for Elekto, both the core code and the deployment of it.  

These recommendations are confidential until fixes are implemented.  The one that is already public is the one about cancelling ballots: #49.

**Comment by ameukam** [comment]
> areas of improvement for Elekto, 

Happy to work on the infrastructure (if needed) aspect of those suggested improvements.

**Comment by 007vedant** [comment]
Hey @jberkus !. I'd be happy to work on this issue under LFX Mentorship'22. I'm expert in Python programming, have an extensive experience in backend development with Flask and Django and have solid fundamentals in SQL and databases.

**Comment by richardgreg** [comment]
Hi, @jberkus I'm an LFX mentee and I'm interested in working on the improvements for Elekto. I'll be submitting my cover letter and resume detailing my relevant skills and experience. Please let me know of any other initial tasks needed. Thanks.

**Comment by jberkus** [comment]
@007vedant @richardgreg glad to hear from you!  Look forward to your LFX applications.

**Comment by khabdrick** [comment]
@jberkus Do potential mentees have to make contributions to the project before they can be considered for the program?

**Comment by jberkus** [comment]
@khabdrick no, although we will be looking for some kind of work on the related technologies.

**Comment by aastha01chauhan** [comment]
Hey @jberkus The concept of Elekto got me interested. I feel it would be great if I get an opportunity to work on its improvements. I am proficient in python programming. This project seems to be in alignment with my tech stack. I would be glad to connect with the community and work on it this spring.

**Comment by RajGM** [comment]
I would love to work on this as well.

**Comment by monalisha31** [comment]
@jberkus This project seems very interesting. I am interested in working on it as a LFX mentee this spring. I have submitted the cover letter and CV as well. Looking forward to your feedback.

**Comment by Dabjazz** [comment]
Hello, @jberkus I went through the website of Elekto, I am happy to help and contribute to this project. I can help with improving the documentation, adding recipes, and many other guides as well. Looking forward to working on this project as an LFX mentee and enhancing my knowledge of K8S.

**Comment by kalkayan** [comment]
We have selected @007vedant as the mentee for this term of the mentorship. Thanks, everyone for your interest in Elekto and for taking the time to submit your applications.

**Comment by jberkus** [comment]
This is resolved, with the release of 0.6.0.  Good work, @007vedant !
