### ISSUE TITLE
Port 0.5-->0.6 upgrade code to MySQL, SQLite

### ISSUE THREAD

**Issue by jberkus** [elekto-io/elekto#67]
Version 0.6 includes a number of database schema changes.  The code for upgrading those changes automatically is currently written only for PostgreSQL.  Ideally, we should have MySQL and SQLite versions.

Here's the current code: https://github.com/elekto-io/elekto/blob/migration/elekto/models/sql.py#L110

Question:
1. Do we have SQLite and MySQL production users who will need to upgrade?
2. Are any of those users willing to help test the upgrade code?

**Comment by emalm** [comment]
We at the the CF Foundation are backing our Elekto instance with MySQL, but not for any particularly good reason (we could just as easily have started with Postgres). Retaining the details of our just-concluded 2022 TOC election would be nice, but not critical, so no need to bother if we're the only ones who would possibly use it.

Also, haha, I've now realized that we deployed a version later than the v0.5 line anyway, effectively at 7c73d4b5a12195e74ceb4dc334a7b95e43124d07 (current head of main), and from https://github.com/elekto-io/elekto/compare/0.5.1...7c73d4b5a12195e74ceb4dc334a7b95e43124d07 it looks like the majority of these schema changes apply already: in fact, maybe everything except some indexes and non-null constraints, and the newly introduced schema version itself. So I expect we're a bad candidate to validate a "normal" v0.5-to-v0.6 migration.

**Comment by jberkus** [comment]
Wait, current Head actually worked to run an election?

**Comment by emalm** [comment]
Apparently! I'm not aware of any problems arising. Is there something that is expected not to work currently?

**Comment by jberkus** [comment]
Nope, just that we never tested that build.

**Comment by jberkus** [comment]
Closing this issue; at this point anyone using MySQL is upgraded, or they started on a later version.
