### ISSUE TITLE
repo link should be elekto.dev?

### ISSUE THREAD

**Issue by BenTheElder** [elekto-io/elekto#71]
(also perhaps the org should move to elekto instead of elekto.io?)

AFAICT elect.io is just a redirect to elekto.dev which is now the canonical site, but this repo sets the about link to elekto.io still.

**Comment by jberkus** [comment]
Sadly, the /elekto org is not available -- it's being squatted.

Profile link updated.

**Comment by BenTheElder** [comment]
thanks!

**Comment by wolftune** [comment]
as elekto.io seems totally down now, I'd urge changing the GitHub repo to list elekto.dev
the redirect isn't functioning
